### ISSUE TITLE
Fix pagination for UAA for users with over 100 spaces/orgs (1/7)

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/logsearch-for-cloudfoundry#39]
In order for a user who(m) has roles in over 100 spaces and organizations, we want to be able to successfully paginate requests to allow them access to the logs for all of the spaces and orgs they belong to on not just the first 100.

## Acceptance Criteria
* [ ] GIVEN an authenticated user has access to all of the logs for all of their spaces and orgs.

## Security considerations
none

## Implementation sketch
[links to background notes, sketches, and/or relevant documentation
* [ ] Update logic in https://github.com/cloud-gov/logsearch-for-cloudfoundry/blob/develop/src/kibana-cf_authentication/server/uaa-provider.js
* [ ] Successfully paginate orgs and spaces when greater than 100.

**Comment by karareinsel** [comment]
Blocked by #1257

**Comment by bengerman13** [comment]
for the link:
blocked by cloud-gov/product#1257

**Comment by karareinsel** [comment]
Should this be moved back into the product repo and pull it back in once Kibana is done?
