### ISSUE TITLE
Add ODfE - open distro for elasticsearch

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/logsearch-for-cloudfoundry#85]
In order to improve security, maintainability, and usability of Kibana, we want to add the ODfE to elasticsearch and kibana

ODfE "Open Distro for Elastic Search" is a community-maintained distribution of  https://opendistro.github.io/for-elasticsearch/

--- 

## Security considerations

This is substituting a well-maintained and tested multi-user interface that will replace our current Kibana authorization. This will improve our ability to maintain boundaries between tenants, but will require review and testing.

## Implementation sketch
https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/
* [ ] add blobs
* [ ] add config
* [ ] update deployment with config

**Comment by markdboyd** [comment]
Superseded by https://github.com/cloud-gov/private/issues/740
